version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels: [ ]
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    groups:
      github-actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /
    labels: [ ]
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /wasm_module
    labels: [ ]
    schedule:
      interval: cron
      cronjob: 0 17 5 * *
    allow:
      - dependency-type: all
    groups:
      cargo-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
