export default [
  { id: 8664, name: 'metalrod', type: 'generic' },
  { id: 8678, name: 'rock', type: 'generic' },
  { id: 8686, name: 'ashlegionspykit', type: 'generic' },
  { id: 8732, name: 'powermatrix', type: 'generic' },
  { id: 8759, name: 'woodenplank', type: 'generic' },
  { id: 8764, name: 'harpyfeathers', type: 'generic' },
  { id: 8801, name: 'orderofwhispersspykit', type: 'generic' },
  { id: 8879, name: 'powerfulpotionofflamelegionslaying', type: 'utility' },
  { id: 8880, name: 'powerfulpotionofcentaurslaying', type: 'utility' },
  { id: 8881, name: 'powerfulpotionofoutlawslaying', type: 'utility' },
  { id: 8882, name: 'powerfulpotionofnightmarecourtslaying', type: 'utility' },
  { id: 8883, name: 'powerfulpotionofsonsofsvanirslaying', type: 'utility' },
  { id: 8884, name: 'powerfulpotionofdestroyerslaying', type: 'utility' },
  { id: 8885, name: 'powerfulpotionofelementalslaying', type: 'utility' },
  { id: 8886, name: 'powerfulpotionofdemonslaying', type: 'utility' },
  { id: 8887, name: 'powerfulpotionofinquestslaying', type: 'utility' },
  { id: 8888, name: 'powerfulpotionofogreslaying', type: 'utility' },
  { id: 8889, name: 'powerfulpotionoficebroodslaying', type: 'utility' },
  { id: 8890, name: 'powerfulpotionofgrawlslaying', type: 'utility' },
  { id: 8891, name: 'powerfulpotionofkraitslaying', type: 'utility' },
  { id: 8892, name: 'powerfulpotionofdredgeslaying', type: 'utility' },
  { id: 8893, name: 'powerfulpotionofundeadslaying', type: 'utility' },
  { id: 9443, name: 'superiorsharpeningstone', type: 'utility' },
  { id: 9461, name: 'mastermaintenanceoil', type: 'utility' },
  { id: 9476, name: 'mastertuningcrystal', type: 'utility' },
  { id: 12452, name: 'omnomberrybar', type: 'food' },
  { id: 12453, name: 'chocolateomnomberrycream', type: 'food' },
  { id: 12454, name: 'spicychocolatecookie', type: 'food' },
  { id: 12455, name: 'omnomberrycookie', type: 'food' },
  { id: 12456, name: 'mangopie', type: 'food' },
  { id: 12457, name: 'omnomberrypie', type: 'food' },
  { id: 12458, name: 'omnomberrycompote', type: 'food' },
  { id: 12459, name: 'omnomberrytart', type: 'food' },
  { id: 12460, name: 'chocolateomnomberrycake', type: 'food' },
  { id: 12461, name: 'bowloftruffleravioli', type: 'food' },
  { id: 12462, name: 'plateoflemongrasspoultry', type: 'food' },
  { id: 12463, name: 'fancytruffleburger', type: 'food' },
  { id: 12464, name: 'rareveggiepizza', type: 'food' },
  { id: 12465, name: 'bowloftrufflerisotto', type: 'food' },
  { id: 12466, name: 'plateoffireflanksteak', type: 'food' },
  { id: 12467, name: 'plateoftrufflesteak', type: 'food' },
  { id: 12468, name: 'plateoforriansteakfrittes', type: 'food' },
  { id: 12469, name: 'plateoftrufflesteakdinner', type: 'food' },
  { id: 12470, name: 'bowloflotusstirfry', type: 'food' },
  { id: 12471, name: 'bowlofseaweedsalad', type: 'food' },
  { id: 12472, name: 'cupoflotusfries', type: 'food' },
  { id: 12473, name: 'loafofomnomberrybread', type: 'food' },
  { id: 12474, name: 'loafofsaffronbread', type: 'food' },
  { id: 12475, name: 'bowlofroastedlotusroot', type: 'food' },
  { id: 12476, name: 'saffronstuffedmushroom', type: 'food' },
  { id: 12477, name: 'bowloffiresalsa', type: 'food' },
  { id: 12478, name: 'bowloftrufflesautee', type: 'food' },
  { id: 12479, name: 'ghostpepperpopper', type: 'food' },
  { id: 12480, name: 'bowlofsaffronscentedpoultrysoup', type: 'food' },
  { id: 12481, name: 'bowloflemongrasspoultrysoup', type: 'food' },
  { id: 12482, name: 'bowloforriantrufflesoup', type: 'food' },
  { id: 12483, name: 'bowloffireveggiechili', type: 'food' },
  { id: 12484, name: 'bowloffiremeatchili', type: 'food' },
  { id: 12485, name: 'bowloffancypotatoandleeksoup', type: 'food' },
  { id: 12486, name: 'bowlofcurrybutternutsquashsoup', type: 'food' },
  { id: 12487, name: 'bowlofcurrypumpkinsoup', type: 'food' },
  { id: 12488, name: 'bowloforriantruffleandmeatstew', type: 'food' },
  { id: 12585, name: 'giantchocolateomnomberrycake', type: 'food' },
  { id: 12586, name: 'trayofchocolateomnomberrycreams', type: 'food' },
  { id: 12587, name: 'trayofmangopies', type: 'food' },
  { id: 12588, name: 'trayofomnomberrybars', type: 'food' },
  { id: 12589, name: 'trayofomnomberrycompote', type: 'food' },
  { id: 12590, name: 'trayofomnomberrycookies', type: 'food' },
  { id: 12591, name: 'trayofomnomberrypies', type: 'food' },
  { id: 12592, name: 'trayofomnomberrytarts', type: 'food' },
  { id: 12593, name: 'trayofspicychocolatecookies', type: 'food' },
  { id: 12633, name: 'feastoffancytruffleburgers', type: 'food' },
  { id: 12634, name: 'feastoffireflanksteak', type: 'food' },
  { id: 12635, name: 'feastoflemongrasspoultry', type: 'food' },
  { id: 12636, name: 'feastoflotusstirfry', type: 'food' },
  { id: 12637, name: 'feastoforriansteakfrittes', type: 'food' },
  { id: 12638, name: 'feastofrareveggiepizzas', type: 'food' },
  { id: 12639, name: 'feastoftruffleravioli', type: 'food' },
  { id: 12640, name: 'potoftrufflerisotto', type: 'food' },
  { id: 12641, name: 'feastoftrufflesteakdinner', type: 'food' },
  { id: 12642, name: 'feastoftrufflesteak', type: 'food' },
  { id: 12678, name: 'feastoffiresalsa', type: 'food' },
  { id: 12679, name: 'feastofghostpepperpoppers', type: 'food' },
  { id: 12680, name: 'feastoflotusfries', type: 'food' },
  { id: 12681, name: 'trayofomnomberrybread', type: 'food' },
  { id: 12682, name: 'feastofroastedlotusroot', type: 'food' },
  { id: 12683, name: 'trayofsaffronbread', type: 'food' },
  { id: 12684, name: 'feastofsaffronstuffedmushrooms', type: 'food' },
  { id: 12685, name: 'feastofseaweedsalad', type: 'food' },
  { id: 12686, name: 'feastoftrufflesautee', type: 'food' },
  { id: 12720, name: 'potofcurrybutternutsquashsoup', type: 'food' },
  { id: 12721, name: 'potofcurrypumpkinsoup', type: 'food' },
  { id: 12722, name: 'potoffancypotatoandleeksoup', type: 'food' },
  { id: 12723, name: 'potoffiremeatchili', type: 'food' },
  { id: 12724, name: 'potoffireveggiechili', type: 'food' },
  { id: 12725, name: 'potoflemongrasspoultrysoup', type: 'food' },
  { id: 12726, name: 'potoforriantruffleandmeatstew', type: 'food' },
  { id: 12727, name: 'potoforriantrufflesoup', type: 'food' },
  { id: 12728, name: 'potofsaffronscentedpoultrysoup', type: 'food' },
  { id: 24548, name: 'fire', type: 'sigil' },
  { id: 24551, name: 'water', type: 'sigil' },
  { id: 24554, name: 'air', type: 'sigil' },
  { id: 24555, name: 'ice', type: 'sigil' },
  { id: 24560, name: 'earth', type: 'sigil' },
  { id: 24561, name: 'rage', type: 'sigil' },
  { id: 24562, name: 'strength', type: 'sigil' },
  { id: 24567, name: 'frailty', type: 'sigil' },
  { id: 24570, name: 'blood', type: 'sigil' },
  { id: 24571, name: 'purity', type: 'sigil' },
  { id: 24572, name: 'nullification', type: 'sigil' },
  { id: 24575, name: 'bloodlust', type: 'sigil' },
  { id: 24578, name: 'corruption', type: 'sigil' },
  { id: 24580, name: 'perception', type: 'sigil' },
  { id: 24582, name: 'life', type: 'sigil' },
  { id: 24583, name: 'demons', type: 'sigil' },
  { id: 24584, name: 'benevolence', type: 'sigil' },
  { id: 24589, name: 'speed', type: 'sigil' },
  { id: 24591, name: 'luck', type: 'sigil' },
  { id: 24592, name: 'stamina', type: 'sigil' },
  { id: 24594, name: 'restoration', type: 'sigil' },
  { id: 24597, name: 'hydromancy', type: 'sigil' },
  { id: 24599, name: 'leeching', type: 'sigil' },
  { id: 24600, name: 'vision', type: 'sigil' },
  { id: 24601, name: 'battle', type: 'sigil' },
  { id: 24605, name: 'geomancy', type: 'sigil' },
  { id: 24607, name: 'energy', type: 'sigil' },
  { id: 24609, name: 'doom', type: 'sigil' },
  { id: 24612, name: 'agony', type: 'sigil' },
  { id: 24615, name: 'force', type: 'sigil' },
  { id: 24618, name: 'accuracy', type: 'sigil' },
  { id: 24621, name: 'peril', type: 'sigil' },
  { id: 24624, name: 'smoldering', type: 'sigil' },
  { id: 24627, name: 'hobbling', type: 'sigil' },
  { id: 24630, name: 'chilling', type: 'sigil' },
  { id: 24632, name: 'venom', type: 'sigil' },
  { id: 24636, name: 'debility', type: 'sigil' },
  { id: 24639, name: 'paralyzation', type: 'sigil' },
  { id: 24642, name: 'undeadslaying', type: 'sigil' },
  { id: 24645, name: 'centaurslaying', type: 'sigil' },
  { id: 24648, name: 'grawlslaying', type: 'sigil' },
  { id: 24651, name: 'icebroodslaying', type: 'sigil' },
  { id: 24654, name: 'destroyerslaying', type: 'sigil' },
  { id: 24655, name: 'ogreslaying', type: 'sigil' },
  { id: 24658, name: 'serpentslaying', type: 'sigil' },
  { id: 24661, name: 'elementalslaying', type: 'sigil' },
  { id: 24664, name: 'demonslaying', type: 'sigil' },
  { id: 24667, name: 'wrath', type: 'sigil' },
  { id: 24672, name: 'madscientists', type: 'sigil' },
  { id: 24675, name: 'smoring', type: 'sigil' },
  { id: 24678, name: 'justice', type: 'sigil' },
  { id: 24681, name: 'dreams', type: 'sigil' },
  { id: 24684, name: 'sorrow', type: 'sigil' },
  { id: 24687, name: 'afflicted', type: 'rune' },
  { id: 24688, name: 'lich', type: 'rune' },
  { id: 24691, name: 'traveler', type: 'rune' },
  { id: 24696, name: 'flock', type: 'rune' },
  { id: 24699, name: 'dolyak', type: 'rune' },
  { id: 24702, name: 'pack', type: 'rune' },
  { id: 24703, name: 'infiltration', type: 'rune' },
  { id: 24708, name: 'mercy', type: 'rune' },
  { id: 24711, name: 'vampirism', type: 'rune' },
  { id: 24714, name: 'strength', type: 'rune' },
  { id: 24717, name: 'rage', type: 'rune' },
  { id: 24720, name: 'speed', type: 'rune' },
  { id: 24723, name: 'eagle', type: 'rune' },
  { id: 24726, name: 'ratasum', type: 'rune' },
  { id: 24729, name: 'hoelbrak', type: 'rune' },
  { id: 24732, name: 'divinity', type: 'rune' },
  { id: 24735, name: 'grove', type: 'rune' },
  { id: 24738, name: 'scavenging', type: 'rune' },
  { id: 24741, name: 'citadel', type: 'rune' },
  { id: 24744, name: 'earth', type: 'rune' },
  { id: 24747, name: 'fire', type: 'rune' },
  { id: 24750, name: 'air', type: 'rune' },
  { id: 24753, name: 'ice', type: 'rune' },
  { id: 24756, name: 'ogre', type: 'rune' },
  { id: 24757, name: 'undead', type: 'rune' },
  { id: 24762, name: 'krait', type: 'rune' },
  { id: 24765, name: 'balthazar', type: 'rune' },
  { id: 24768, name: 'dwayna', type: 'rune' },
  { id: 24771, name: 'melandru', type: 'rune' },
  { id: 24776, name: 'lyssa', type: 'rune' },
  { id: 24779, name: 'grenth', type: 'rune' },
  { id: 24782, name: 'privateer', type: 'rune' },
  { id: 24785, name: 'golemancer', type: 'rune' },
  { id: 24788, name: 'centaur', type: 'rune' },
  { id: 24791, name: 'wurm', type: 'rune' },
  { id: 24794, name: 'svanir', type: 'rune' },
  { id: 24797, name: 'flamelegion', type: 'rune' },
  { id: 24800, name: 'elementalist', type: 'rune' },
  { id: 24803, name: 'mesmer', type: 'rune' },
  { id: 24806, name: 'necromancer', type: 'rune' },
  { id: 24809, name: 'ghostslaying', type: 'sigil' },
  { id: 24812, name: 'engineer', type: 'rune' },
  { id: 24815, name: 'ranger', type: 'rune' },
  { id: 24818, name: 'thief', type: 'rune' },
  { id: 24821, name: 'warrior', type: 'rune' },
  { id: 24824, name: 'guardian', type: 'rune' },
  { id: 24827, name: 'trooper', type: 'rune' },
  { id: 24830, name: 'adventurer', type: 'rune' },
  { id: 24833, name: 'brawler', type: 'rune' },
  { id: 24836, name: 'scholar', type: 'rune' },
  { id: 24839, name: 'water', type: 'rune' },
  { id: 24842, name: 'monk', type: 'rune' },
  { id: 24845, name: 'aristocracy', type: 'rune' },
  { id: 24848, name: 'nightmare', type: 'rune' },
  { id: 24851, name: 'forgeman', type: 'rune' },
  { id: 24854, name: 'baelfire', type: 'rune' },
  { id: 24857, name: 'sanctuary', type: 'rune' },
  { id: 24860, name: 'orr', type: 'rune' },
  { id: 24865, name: 'celerity', type: 'sigil' },
  { id: 24868, name: 'impact', type: 'sigil' },
  { id: 36044, name: 'madking', type: 'rune' },
  { id: 36053, name: 'night', type: 'sigil' },
  { id: 36083, name: 'omnomberryghost', type: 'food' },
  { id: 36084, name: 'spicypumpkincookie', type: 'food' },
  { id: 36092, name: 'powerfulpotionofhalloweenslaying', type: 'utility' },
  { id: 36793, name: 'bowloftropicalfruitsalad', type: 'food' },
  { id: 36841, name: 'bowloftropicalmousse', type: 'food' },
  {
    id: 37039,
    name: 'betafractalcapacitorinfused',
    type: 'backitem',
    affix: 'berserker',
  },
  { id: 37125, name: 'healingagonyinfusion', type: 'infusion' },
  { id: 37130, name: 'malignagonyinfusion', type: 'infusion' },
  { id: 37131, name: 'mightyagonyinfusion', type: 'infusion' },
  { id: 37132, name: 'preciseagonyinfusion', type: 'infusion' },
  { id: 37135, name: 'resilientagonyinfusion', type: 'infusion' },
  { id: 37136, name: 'vitalagonyinfusion', type: 'infusion' },
  { id: 37912, name: 'karkaslaying', type: 'sigil' },
  { id: 38206, name: 'altruism', type: 'rune' },
  { id: 38210, name: 'bowlofsaffronmangoicecream', type: 'food' },
  { id: 38294, name: 'generosity', type: 'sigil' },
  {
    id: 39232,
    name: 'magistersfieldjournal',
    type: 'accessory',
    affix: 'berserker',
  },
  { id: 39233, name: 'altheasashes', type: 'accessory', affix: 'berserker' },
  { id: 39242, name: 'celestialsigil', type: 'accessory', affix: 'celestial' },
  {
    id: 39243,
    name: 'ancientmursaattoken',
    type: 'accessory',
    affix: 'celestial',
  },
  { id: 39272, name: 'callofthewild', type: 'amulet', affix: 'berserker' },
  { id: 39282, name: 'theeyesofabaddon', type: 'amulet', affix: 'celestial' },
  {
    id: 39546,
    name: 'preservedredirisflower',
    type: 'accessory',
    affix: 'cleric',
  },
  { id: 39547, name: 'kurzickbauble', type: 'accessory', affix: 'cleric' },
  { id: 39566, name: 'amuletofprotection', type: 'amulet', affix: 'cleric' },
  { id: 41561, name: 'carrotsouffl', type: 'food' },
  { id: 41562, name: 'bowlofrefugeesbeetsoup', type: 'food' },
  { id: 41563, name: 'spicymarinatedmushroom', type: 'food' },
  { id: 41564, name: 'plateoffrostgorgeclams', type: 'food' },
  { id: 41565, name: 'bowlofgarlickalesautee', type: 'food' },
  { id: 41566, name: 'mushroomloaf', type: 'food' },
  { id: 41567, name: 'plateofspicyherbedchicken', type: 'food' },
  { id: 41568, name: 'bowlofzestyturnipsoup', type: 'food' },
  { id: 41569, name: 'bowlofsweetandspicybutternutsquashsoup', type: 'food' },
  { id: 42427, name: 'potionofkarkaslaying', type: 'utility' },
  { id: 42428, name: 'potionofkarkatoughness', type: 'utility' },
  { id: 43449, name: 'potentmastertuningcrystal', type: 'utility' },
  { id: 43450, name: 'potentmastermaintenanceoil', type: 'utility' },
  { id: 43451, name: 'potentsuperiorsharpeningstone', type: 'utility' },
  { id: 44642, name: 'watchworkportaldevice', type: 'generic' },
  { id: 44944, name: 'bursting', type: 'sigil' },
  { id: 44947, name: 'renewal', type: 'sigil' },
  { id: 44950, name: 'malice', type: 'sigil' },
  { id: 44951, name: 'exuberance', type: 'rune' },
  { id: 44956, name: 'tormenting', type: 'rune' },
  { id: 44957, name: 'perplexity', type: 'rune' },
  { id: 46759, name: 'zojjasreaver', type: 'axe', affix: 'berserker' },
  { id: 46760, name: 'zojjasrazor', type: 'dagger', affix: 'berserker' },
  { id: 46761, name: 'zojjasartifact', type: 'focus', affix: 'berserker' },
  { id: 46762, name: 'zojjasclaymore', type: 'greatsword', affix: 'berserker' },
  { id: 46763, name: 'zojjaswarhammer', type: 'hammer', affix: 'berserker' },
  { id: 46764, name: 'zojjasimpaler', type: 'harpoon', affix: 'berserker' },
  { id: 46765, name: 'zojjasgreatbow', type: 'longbow', affix: 'berserker' },
  { id: 46766, name: 'zojjasflangedmace', type: 'mace', affix: 'berserker' },
  { id: 46767, name: 'zojjasrevolver', type: 'pistol', affix: 'berserker' },
  { id: 46768, name: 'zojjasmusket', type: 'rifle', affix: 'berserker' },
  { id: 46769, name: 'zojjaswand', type: 'scepter', affix: 'berserker' },
  { id: 46770, name: 'zojjasbastion', type: 'shield', affix: 'berserker' },
  { id: 46771, name: 'zojjasshortbow', type: 'shortbow', affix: 'berserker' },
  { id: 46772, name: 'zojjasharpoongun', type: 'speargun', affix: 'berserker' },
  { id: 46773, name: 'zojjasspire', type: 'staff', affix: 'berserker' },
  { id: 46774, name: 'zojjasblade', type: 'sword', affix: 'berserker' },
  { id: 46775, name: 'zojjasbrazier', type: 'torch', affix: 'berserker' },
  { id: 46776, name: 'zojjastrident', type: 'trident', affix: 'berserker' },
  { id: 46777, name: 'zojjasherald', type: 'warhorn', affix: 'berserker' },
  { id: 47006, name: 'wupwupreaver', type: 'axe', affix: 'celestial' },
  { id: 47007, name: 'wupwuprazor', type: 'dagger', affix: 'celestial' },
  { id: 47008, name: 'wupwupartifact', type: 'focus', affix: 'celestial' },
  { id: 47009, name: 'wupwupclaymore', type: 'greatsword', affix: 'celestial' },
  { id: 47010, name: 'wupwupwarhammer', type: 'hammer', affix: 'celestial' },
  { id: 47011, name: 'wupwupimpaler', type: 'harpoon', affix: 'celestial' },
  { id: 47012, name: 'wupwupgreatbow', type: 'longbow', affix: 'celestial' },
  { id: 47013, name: 'wupwupflangedmace', type: 'mace', affix: 'celestial' },
  { id: 47014, name: 'wupwuprevolver', type: 'pistol', affix: 'celestial' },
  { id: 47015, name: 'wupwupmusket', type: 'rifle', affix: 'celestial' },
  { id: 47016, name: 'wupwupwand', type: 'scepter', affix: 'celestial' },
  { id: 47017, name: 'wupwupbastion', type: 'shield', affix: 'celestial' },
  { id: 47018, name: 'wupwupshortbow', type: 'shortbow', affix: 'celestial' },
  { id: 47019, name: 'wupwupharpoongun', type: 'speargun', affix: 'celestial' },
  { id: 47020, name: 'wupwupspire', type: 'staff', affix: 'celestial' },
  { id: 47021, name: 'wupwupblade', type: 'sword', affix: 'celestial' },
  { id: 47022, name: 'wupwupbrazier', type: 'torch', affix: 'celestial' },
  { id: 47023, name: 'wupwuptrident', type: 'trident', affix: 'celestial' },
  { id: 47024, name: 'wupwupherald', type: 'warhorn', affix: 'celestial' },
  { id: 47025, name: 'theodosussreaver', type: 'axe', affix: 'cleric' },
  { id: 47026, name: 'theodosussrazor', type: 'dagger', affix: 'cleric' },
  { id: 47027, name: 'theodosussartifact', type: 'focus', affix: 'cleric' },
  {
    id: 47028,
    name: 'theodosussclaymore',
    type: 'greatsword',
    affix: 'cleric',
  },
  { id: 47029, name: 'theodosusswarhammer', type: 'hammer', affix: 'cleric' },
  { id: 47030, name: 'theodosussimpaler', type: 'harpoon', affix: 'cleric' },
  { id: 47031, name: 'theodosussgreatbow', type: 'longbow', affix: 'cleric' },
  { id: 47032, name: 'theodosussflangedmace', type: 'mace', affix: 'cleric' },
  { id: 47033, name: 'theodosussrevolver', type: 'pistol', affix: 'cleric' },
  { id: 47034, name: 'theodosussmusket', type: 'rifle', affix: 'cleric' },
  { id: 47035, name: 'theodosusswand', type: 'scepter', affix: 'cleric' },
  { id: 47036, name: 'theodosussbastion', type: 'shield', affix: 'cleric' },
  { id: 47037, name: 'theodosussshortbow', type: 'shortbow', affix: 'cleric' },
  {
    id: 47038,
    name: 'theodosussharpoongun',
    type: 'speargun',
    affix: 'cleric',
  },
  { id: 47039, name: 'theodosussspire', type: 'staff', affix: 'cleric' },
  { id: 47040, name: 'theodosussblade', type: 'sword', affix: 'cleric' },
  { id: 47041, name: 'theodosussbrazier', type: 'torch', affix: 'cleric' },
  { id: 47042, name: 'theodosusstrident', type: 'trident', affix: 'cleric' },
  { id: 47043, name: 'theodosussherald', type: 'warhorn', affix: 'cleric' },
  { id: 47044, name: 'sorossreaver', type: 'axe', affix: 'assassin' },
  { id: 47045, name: 'sorossrazor', type: 'dagger', affix: 'assassin' },
  { id: 47046, name: 'sorossartifact', type: 'focus', affix: 'assassin' },
  { id: 47047, name: 'sorossclaymore', type: 'greatsword', affix: 'assassin' },
  { id: 47048, name: 'sorosswarhammer', type: 'hammer', affix: 'assassin' },
  { id: 47049, name: 'sorossimpaler', type: 'harpoon', affix: 'assassin' },
  { id: 47050, name: 'sorossgreatbow', type: 'longbow', affix: 'assassin' },
  { id: 47051, name: 'sorossflangedmace', type: 'mace', affix: 'assassin' },
  { id: 47052, name: 'sorossrevolver', type: 'pistol', affix: 'assassin' },
  { id: 47053, name: 'sorossmusket', type: 'rifle', affix: 'assassin' },
  { id: 47054, name: 'sorosswand', type: 'scepter', affix: 'assassin' },
  { id: 47055, name: 'sorossbastion', type: 'shield', affix: 'assassin' },
  { id: 47056, name: 'sorossshortbow', type: 'shortbow', affix: 'assassin' },
  { id: 47057, name: 'sorossharpoongun', type: 'speargun', affix: 'assassin' },
  { id: 47058, name: 'sorossspire', type: 'staff', affix: 'assassin' },
  { id: 47059, name: 'sorossblade', type: 'sword', affix: 'assassin' },
  { id: 47060, name: 'sorossbrazier', type: 'torch', affix: 'assassin' },
  { id: 47061, name: 'sorosstrident', type: 'trident', affix: 'assassin' },
  { id: 47062, name: 'sorossherald', type: 'warhorn', affix: 'assassin' },
  { id: 47908, name: 'sunless', type: 'rune' },
  {
    id: 47928,
    name: 'wupwupgreaves',
    type: 'boots',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47929,
    name: 'wupwupbreastplate',
    type: 'coat',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47930,
    name: 'wupwupwarfists',
    type: 'gloves',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47931,
    name: 'wupwupvisor',
    type: 'helm',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47932,
    name: 'wupwuptassets',
    type: 'leggings',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47933,
    name: 'wupwuppauldrons',
    type: 'shoulders',
    affix: 'celestial',
    weight: 'heavy',
  },
  {
    id: 47934,
    name: 'wupwupfootwear',
    type: 'boots',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47935,
    name: 'wupwupdoublet',
    type: 'coat',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47936,
    name: 'wupwupwristguards',
    type: 'gloves',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47937,
    name: 'wupwupmasque',
    type: 'helm',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47938,
    name: 'wupwupbreeches',
    type: 'leggings',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47939,
    name: 'wupwupepaulets',
    type: 'shoulders',
    affix: 'celestial',
    weight: 'light',
  },
  {
    id: 47940,
    name: 'wupwupstriders',
    type: 'boots',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 47941,
    name: 'wupwupguise',
    type: 'coat',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 47942,
    name: 'wupwupgrips',
    type: 'gloves',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 47943,
    name: 'wupwupvisage',
    type: 'helm',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 47944,
    name: 'wupwupleggings',
    type: 'leggings',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 47945,
    name: 'wupwupshoulderguard',
    type: 'shoulders',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 48000,
    name: 'tateossgreaves',
    type: 'boots',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48001,
    name: 'tateossbreastplate',
    type: 'coat',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48002,
    name: 'tateosswarfists',
    type: 'gloves',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48003,
    name: 'tateossvisor',
    type: 'helm',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48004,
    name: 'tateosstassets',
    type: 'leggings',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48005,
    name: 'tateosspauldrons',
    type: 'shoulders',
    affix: 'cleric',
    weight: 'heavy',
  },
  {
    id: 48006,
    name: 'tateossfootwear',
    type: 'boots',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48007,
    name: 'tateossdoublet',
    type: 'coat',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48008,
    name: 'tateosswristguards',
    type: 'gloves',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48009,
    name: 'tateossmasque',
    type: 'helm',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48010,
    name: 'tateossbreeches',
    type: 'leggings',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48011,
    name: 'tateossepaulets',
    type: 'shoulders',
    affix: 'cleric',
    weight: 'light',
  },
  {
    id: 48012,
    name: 'tateossstriders',
    type: 'boots',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48013,
    name: 'tateossguise',
    type: 'coat',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48014,
    name: 'tateossgrips',
    type: 'gloves',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48015,
    name: 'tateossvisage',
    type: 'helm',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48016,
    name: 'tateossleggings',
    type: 'leggings',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48017,
    name: 'tateossshoulderguard',
    type: 'shoulders',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 48072,
    name: 'zojjasgreaves',
    type: 'boots',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48073,
    name: 'zojjasbreastplate',
    type: 'coat',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48074,
    name: 'zojjaswarfists',
    type: 'gloves',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48075,
    name: 'zojjasvisor',
    type: 'helm',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48076,
    name: 'zojjastassets',
    type: 'leggings',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48077,
    name: 'zojjaspauldrons',
    type: 'shoulders',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 48078,
    name: 'zojjasfootwear',
    type: 'boots',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48079,
    name: 'zojjasdoublet',
    type: 'coat',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48080,
    name: 'zojjaswristguards',
    type: 'gloves',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48081,
    name: 'zojjasmasque',
    type: 'helm',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48082,
    name: 'zojjasbreeches',
    type: 'leggings',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48083,
    name: 'zojjasepaulets',
    type: 'shoulders',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 48084,
    name: 'zojjasstriders',
    type: 'boots',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48085,
    name: 'zojjasguise',
    type: 'coat',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48086,
    name: 'zojjasgrips',
    type: 'gloves',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48087,
    name: 'zojjasvisage',
    type: 'helm',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48088,
    name: 'zojjasleggings',
    type: 'leggings',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48089,
    name: 'zojjasshoulderguard',
    type: 'shoulders',
    affix: 'berserker',
    weight: 'medium',
  },
  {
    id: 48126,
    name: 'saphirsgreaves',
    type: 'boots',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48127,
    name: 'saphirsbreastplate',
    type: 'coat',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48128,
    name: 'saphirswarfists',
    type: 'gloves',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48129,
    name: 'saphirsvisor',
    type: 'helm',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48130,
    name: 'saphirstassets',
    type: 'leggings',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48131,
    name: 'saphirspauldrons',
    type: 'shoulders',
    affix: 'assassin',
    weight: 'heavy',
  },
  {
    id: 48132,
    name: 'saphirsfootwear',
    type: 'boots',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48133,
    name: 'saphirsdoublet',
    type: 'coat',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48134,
    name: 'saphirswristguards',
    type: 'gloves',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48135,
    name: 'saphirsmasque',
    type: 'helm',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48136,
    name: 'saphirsbreeches',
    type: 'leggings',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48137,
    name: 'saphirsepaulets',
    type: 'shoulders',
    affix: 'assassin',
    weight: 'light',
  },
  {
    id: 48138,
    name: 'saphirsstriders',
    type: 'boots',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 48139,
    name: 'saphirsguise',
    type: 'coat',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 48140,
    name: 'saphirsgrips',
    type: 'gloves',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 48141,
    name: 'saphirsvisage',
    type: 'helm',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 48142,
    name: 'saphirsleggings',
    type: 'leggings',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 48143,
    name: 'saphirsshoulderguard',
    type: 'shoulders',
    affix: 'assassin',
    weight: 'medium',
  },
  { id: 48907, name: 'antitoxin', type: 'rune' },
  { id: 48911, name: 'torment', type: 'sigil' },
  { id: 48915, name: 'toxicsharpeningstone', type: 'utility' },
  { id: 48916, name: 'toxicmaintenanceoil', type: 'utility' },
  { id: 48917, name: 'toxicfocusingcrystal', type: 'utility' },
  { id: 48921, name: 'bowlofmarjorysexperimentalchili', type: 'food' },
  { id: 49457, name: 'momentum', type: 'sigil' },
  { id: 49460, name: 'resistance', type: 'rune' },
  { id: 49940, name: 'executioneraxetoy', type: 'gizmo' },
  { id: 50082, name: 'powerfulpotionofslayingscarletsarmies', type: 'utility' },
  { id: 63366, type: 'rune' },
  { id: 66523, name: 'bowlofcactusfruitsalad', type: 'food' },
  { id: 66525, name: 'potofsweetandspicybeans', type: 'food' },
  { id: 66526, name: 'pricklypearstuffednopal', type: 'food' },
  { id: 66527, name: 'loafofcandycactuscornbread', type: 'food' },
  { id: 66528, name: 'bowlofsweetandspicybeans', type: 'food' },
  { id: 66529, name: 'bowlofblackpeppercactussalad', type: 'food' },
  { id: 66530, name: 'bowlofnopalitossaut', type: 'food' },
  { id: 66531, name: 'bowlofcactussoup', type: 'food' },
  { id: 66532, name: 'feastofnopalitossaut', type: 'food' },
  { id: 66533, name: 'feastofcactusfruitsalad', type: 'food' },
  { id: 66534, name: 'feastofblackpeppercactussalad', type: 'food' },
  { id: 66535, name: 'feastofroastedcactus', type: 'food' },
  { id: 66536, name: 'plateofroastedcactus', type: 'food' },
  { id: 66538, name: 'pricklypearpie', type: 'food' },
  { id: 66539, name: 'bowlofpricklypearsorbet', type: 'food' },
  { id: 67183, name: 'ogresharpeningstone', type: 'utility' },
  { id: 67184, name: 'hylekmaintenanceoil', type: 'utility' },
  { id: 67185, name: 'kraittuningcrystal', type: 'utility' },
  { id: 67298, name: 'delanascoinpurse', type: 'accessory', affix: 'assassin' },
  { id: 67302, name: 'zhaitansclaw', type: 'accessory', affix: 'assassin' },
  { id: 67339, name: 'trapper', type: 'rune' },
  { id: 67340, name: 'cleansing', type: 'sigil' },
  { id: 67341, name: 'cruelty', type: 'sigil' },
  { id: 67342, name: 'radiance', type: 'rune' },
  { id: 67343, name: 'incapacitation', type: 'sigil' },
  { id: 67344, name: 'evasion', type: 'rune' },
  { id: 67367, name: 'lumpofcrystallizednougat', type: 'utility' },
  { id: 67368, name: 'sharpeningskull', type: 'utility' },
  { id: 67371, name: 'flaskofpumpkinoil', type: 'utility' },
  {
    id: 67442,
    name: 'veratasmasque',
    type: 'helm',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67443,
    name: 'veratasshoulderguard',
    type: 'shoulders',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67444,
    name: 'veratasleggings',
    type: 'leggings',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67445,
    name: 'veratasvisage',
    type: 'helm',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67446,
    name: 'veratasgrips',
    type: 'gloves',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67447,
    name: 'veratasguise',
    type: 'coat',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67448,
    name: 'veratasstriders',
    type: 'boots',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 67449,
    name: 'veratasepaulets',
    type: 'shoulders',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67450,
    name: 'veratasbreeches',
    type: 'leggings',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67451,
    name: 'veratasgreaves',
    type: 'boots',
    affix: 'sinister',
    weight: 'heavy',
  },
  {
    id: 67452,
    name: 'verataswristguards',
    type: 'gloves',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67453,
    name: 'veratasdoublet',
    type: 'coat',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67454,
    name: 'veratasfootwear',
    type: 'boots',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 67455,
    name: 'verataspauldrons',
    type: 'shoulders',
    affix: 'sinister',
    weight: 'heavy',
  },
  {
    id: 67456,
    name: 'veratastassets',
    type: 'leggings',
    affix: 'sinister',
    weight: 'heavy',
  },
  {
    id: 67457,
    name: 'veratasvisor',
    type: 'helm',
    affix: 'sinister',
    weight: 'heavy',
  },
  {
    id: 67458,
    name: 'verataswarfists',
    type: 'gloves',
    affix: 'sinister',
    weight: 'heavy',
  },
  {
    id: 67459,
    name: 'veratasbreastplate',
    type: 'coat',
    affix: 'sinister',
    weight: 'heavy',
  },
  { id: 67522, name: 'bountifultuningcrystal', type: 'utility' },
  { id: 67524, name: 'furioustuningcrystal', type: 'utility' },
  { id: 67528, name: 'bountifulmaintenanceoil', type: 'utility' },
  { id: 67529, name: 'furiousmaintenanceoil', type: 'utility' },
  { id: 67530, name: 'furioussharpeningstone', type: 'utility' },
  { id: 67531, name: 'bountifulsharpeningstone', type: 'utility' },
  { id: 67894, name: 'caithesremorse', type: 'accessory', affix: 'sinister' },
  { id: 67896, name: 'caithesblossom', type: 'accessory', affix: 'sinister' },
  { id: 67898, name: 'wynneslocket', type: 'amulet', affix: 'sinister' },
  { id: 67912, name: 'defender', type: 'rune' },
  { id: 67913, name: 'blight', type: 'sigil' },
  { id: 67934, name: 'veratasimpaler', type: 'harpoon', affix: 'sinister' },
  { id: 67935, name: 'veratastrident', type: 'trident', affix: 'sinister' },
  { id: 67936, name: 'veratasherald', type: 'warhorn', affix: 'sinister' },
  { id: 67937, name: 'veratasbrazier', type: 'torch', affix: 'sinister' },
  { id: 67938, name: 'veratasblade', type: 'sword', affix: 'sinister' },
  { id: 67939, name: 'veratasspire', type: 'staff', affix: 'sinister' },
  { id: 67940, name: 'veratasharpoongun', type: 'speargun', affix: 'sinister' },
  { id: 67941, name: 'veratasshortbow', type: 'shortbow', affix: 'sinister' },
  { id: 67942, name: 'veratasbastion', type: 'shield', affix: 'sinister' },
  { id: 67943, name: 'verataswand', type: 'scepter', affix: 'sinister' },
  { id: 67944, name: 'veratasreaver', type: 'axe', affix: 'sinister' },
  { id: 67945, name: 'veratasrevolver', type: 'pistol', affix: 'sinister' },
  { id: 67946, name: 'veratasflangedmace', type: 'mace', affix: 'sinister' },
  { id: 67947, name: 'veratasgreatbow', type: 'longbow', affix: 'sinister' },
  { id: 67948, name: 'veratasrazor', type: 'dagger', affix: 'sinister' },
  { id: 67949, name: 'verataswarhammer', type: 'hammer', affix: 'sinister' },
  { id: 67950, name: 'veratasclaymore', type: 'greatsword', affix: 'sinister' },
  { id: 67951, name: 'veratasartifact', type: 'focus', affix: 'sinister' },
  { id: 67952, name: 'veratasmusket', type: 'rifle', affix: 'sinister' },
  { id: 68436, name: 'mischief', type: 'sigil' },
  { id: 68437, name: 'snowfall', type: 'rune' },
  { id: 68633, name: 'friedgoldendumpling', type: 'food' },
  { id: 68634, name: 'deliciousriceball', type: 'food' },
  { id: 69370, name: 'revenant', type: 'rune' },
  {
    id: 70414,
    name: 'maklainsbreeches',
    type: 'leggings',
    affix: 'minstrel',
    weight: 'light',
  },
  { id: 70450, name: 'druid', type: 'rune' },
  { id: 70504, name: 'yassithsgreatbow', type: 'longbow', affix: 'viper' },
  {
    id: 70538,
    name: 'saphirsmetalbreather',
    type: 'helmaquatic',
    affix: 'assassin',
    weight: 'heavy',
  },
  { id: 70600, name: 'leadership', type: 'rune' },
  {
    id: 70641,
    name: 'yassithsleggings',
    type: 'leggings',
    affix: 'viper',
    weight: 'medium',
  },
  { id: 70687, name: 'yassithstrident', type: 'trident', affix: 'viper' },
  {
    id: 70695,
    name: 'attunedplaguesignetinfused',
    type: 'ring',
    affix: 'sinister',
  },
  {
    id: 70712,
    name: 'wupwupleatherbreather',
    type: 'helmaquatic',
    affix: 'celestial',
    weight: 'medium',
  },
  {
    id: 70794,
    name: 'maklainsbreastplate',
    type: 'coat',
    affix: 'minstrel',
    weight: 'heavy',
  },
  { id: 70825, name: 'draining', type: 'sigil' },
  { id: 70829, name: 'reaper', type: 'rune' },
  {
    id: 70834,
    name: 'maklainsguise',
    type: 'coat',
    affix: 'minstrel',
    weight: 'medium',
  },
  { id: 70838, name: 'yassithsblade', type: 'sword', affix: 'viper' },
  { id: 71007, name: 'yassithsclaymore', type: 'greatsword', affix: 'viper' },
  { id: 71116, name: 'maklainsherald', type: 'warhorn', affix: 'minstrel' },
  { id: 71130, name: 'ruthlessness', type: 'sigil' },
  {
    id: 71205,
    name: 'saphirsclothbreather',
    type: 'helmaquatic',
    affix: 'assassin',
    weight: 'light',
  },
  { id: 71276, name: 'scrapper', type: 'rune' },
  { id: 71387, name: 'yassithsspire', type: 'staff', affix: 'viper' },
  {
    id: 71406,
    name: 'tateossmetalbreather',
    type: 'helmaquatic',
    affix: 'cleric',
    weight: 'heavy',
  },
  { id: 71425, name: 'berserker', type: 'rune' },
  {
    id: 71436,
    name: 'yassithsdoublet',
    type: 'coat',
    affix: 'viper',
    weight: 'light',
  },
  {
    id: 71456,
    name: 'maklainsgreaves',
    type: 'boots',
    affix: 'minstrel',
    weight: 'heavy',
  },
  { id: 71457, name: 'maklainsflangedmace', type: 'mace', affix: 'minstrel' },
  { id: 71584, name: 'yassithsartifact', type: 'focus', affix: 'viper' },
  { id: 71691, name: 'writofmasterfulspeed', type: 'utility' },
  {
    id: 71726,
    name: 'attunedveratassearedringinfused',
    type: 'ring',
    affix: 'sinister',
  },
  { id: 71797, name: 'plateofjerkpoultry', type: 'food' },
  { id: 71826, name: 'bowlofpassionfruittapiocapudding', type: 'food' },
  { id: 71944, name: 'yassithsbastion', type: 'shield', affix: 'viper' },
  { id: 72092, name: 'agility', type: 'sigil' },
  { id: 72188, name: 'maklainsartifact', type: 'focus', affix: 'minstrel' },
  {
    id: 72221,
    name: 'wupwupmetalbreather',
    type: 'helmaquatic',
    affix: 'celestial',
    weight: 'heavy',
  },
  { id: 72239, name: 'yassithsrevolver', type: 'pistol', affix: 'viper' },
  {
    id: 72259,
    name: 'yassithsshoulderguard',
    type: 'shoulders',
    affix: 'viper',
    weight: 'medium',
  },
  { id: 72279, name: 'yassithsmusket', type: 'rifle', affix: 'viper' },
  {
    id: 72280,
    name: 'zojjasleatherbreather',
    type: 'helmaquatic',
    affix: 'berserker',
    weight: 'medium',
  },
  { id: 72339, name: 'concentration', type: 'sigil' },
  { id: 72510, name: 'writofmasterfulmalice', type: 'utility' },
  { id: 72532, name: 'thesisonstudiedspeed', type: 'utility' },
  {
    id: 72548,
    name: 'yassithsgreaves',
    type: 'boots',
    affix: 'viper',
    weight: 'heavy',
  },
  {
    id: 72557,
    name: 'yassithspauldrons',
    type: 'shoulders',
    affix: 'viper',
    weight: 'heavy',
  },
  {
    id: 72567,
    name: 'veratasleatherbreather',
    type: 'helmaquatic',
    affix: 'sinister',
    weight: 'medium',
  },
  {
    id: 72698,
    name: 'maklainsvisor',
    type: 'helm',
    affix: 'minstrel',
    weight: 'heavy',
  },
  { id: 72852, name: 'daredevil', type: 'rune' },
  { id: 72872, name: 'absorption', type: 'sigil' },
  { id: 72912, name: 'thorns', type: 'rune' },
  {
    id: 72919,
    name: 'veratasclothbreather',
    type: 'helmaquatic',
    affix: 'sinister',
    weight: 'light',
  },
  {
    id: 72932,
    name: 'attunedhealingsignetinfused',
    type: 'ring',
    affix: 'cleric',
  },
  {
    id: 73009,
    name: 'maklainspauldrons',
    type: 'shoulders',
    affix: 'minstrel',
    weight: 'heavy',
  },
  { id: 73191, name: 'writofmasterfulstrength', type: 'utility' },
  { id: 73220, name: 'maklainswand', type: 'scepter', affix: 'minstrel' },
  { id: 73221, name: 'bowloflemongrassmusselpasta', type: 'food' },
  {
    id: 73225,
    name: 'yassithsepaulets',
    type: 'shoulders',
    affix: 'viper',
    weight: 'light',
  },
  {
    id: 73365,
    name: 'maklainsharpoongun',
    type: 'speargun',
    affix: 'minstrel',
  },
  { id: 73399, name: 'chronomancer', type: 'rune' },
  { id: 73479, name: 'maklainstrident', type: 'trident', affix: 'minstrel' },
  { id: 73497, name: 'maklainsmusket', type: 'rifle', affix: 'minstrel' },
  { id: 73532, name: 'rending', type: 'sigil' },
  { id: 73549, name: 'maklainsrevolver', type: 'pistol', affix: 'minstrel' },
  { id: 73580, name: 'yassithsimpaler', type: 'harpoon', affix: 'viper' },
  { id: 73653, name: 'durability', type: 'rune' },
  {
    id: 73670,
    name: 'maklainsepaulets',
    type: 'shoulders',
    affix: 'minstrel',
    weight: 'light',
  },
  {
    id: 73756,
    name: 'attuneddruidscircleinfused',
    type: 'ring',
    affix: 'cleric',
  },
  { id: 73788, name: 'jerkpoultryandnopalflatbreadsandwich', type: 'food' },
  {
    id: 73813,
    name: 'attunedsolariacircleofthesuninfused',
    type: 'ring',
    affix: 'celestial',
  },
  {
    id: 73852,
    name: 'yassithswristguards',
    type: 'gloves',
    affix: 'viper',
    weight: 'light',
  },
  {
    id: 73854,
    name: 'yassithsstriders',
    type: 'boots',
    affix: 'viper',
    weight: 'medium',
  },
  { id: 73948, name: 'maklainsgreatbow', type: 'longbow', affix: 'minstrel' },
  {
    id: 73970,
    name: 'maklainsmasque',
    type: 'helm',
    affix: 'minstrel',
    weight: 'light',
  },
  { id: 74034, name: 'yassithsharpoongun', type: 'speargun', affix: 'viper' },
  { id: 74179, name: 'yassithsrazor', type: 'dagger', affix: 'viper' },
  {
    id: 74264,
    name: 'yassithsfootwear',
    type: 'boots',
    affix: 'viper',
    weight: 'light',
  },
  { id: 74326, name: 'transference', type: 'sigil' },
  {
    id: 74333,
    name: 'tateossleatherbreather',
    type: 'helmaquatic',
    affix: 'cleric',
    weight: 'medium',
  },
  {
    id: 74353,
    name: 'zojjasmetalbreather',
    type: 'helmaquatic',
    affix: 'berserker',
    weight: 'heavy',
  },
  {
    id: 74357,
    name: 'yassithsvisage',
    type: 'helm',
    affix: 'viper',
    weight: 'medium',
  },
  { id: 74363, name: 'yassithswarhammer', type: 'hammer', affix: 'viper' },
  {
    id: 74412,
    name: 'yassithsvisor',
    type: 'helm',
    affix: 'viper',
    weight: 'heavy',
  },
  {
    id: 74448,
    name: 'maklainsdoublet',
    type: 'coat',
    affix: 'minstrel',
    weight: 'light',
  },
  { id: 74569, name: 'yassithsshortbow', type: 'shortbow', affix: 'viper' },
  { id: 74748, name: 'maklainsbastion', type: 'shield', affix: 'minstrel' },
  { id: 74905, name: 'maklainsreaver', type: 'axe', affix: 'minstrel' },
  { id: 74969, name: 'plateofmusselsgnashblade', type: 'food' },
  { id: 74978, name: 'dragonhunter', type: 'rune' },
  {
    id: 75022,
    name: 'maklainsvisage',
    type: 'helm',
    affix: 'minstrel',
    weight: 'medium',
  },
  { id: 75126, name: 'sliceofallspicecake', type: 'food' },
  {
    id: 75142,
    name: 'maklainswarfists',
    type: 'gloves',
    affix: 'minstrel',
    weight: 'heavy',
  },
  { id: 75200, name: 'maklainsspire', type: 'staff', affix: 'minstrel' },
  { id: 75325, name: 'yassithsherald', type: 'warhorn', affix: 'viper' },
  {
    id: 75340,
    name: 'maklainsleggings',
    type: 'leggings',
    affix: 'minstrel',
    weight: 'medium',
  },
  {
    id: 75349,
    name: 'maklainsfootwear',
    type: 'boots',
    affix: 'minstrel',
    weight: 'light',
  },
  {
    id: 75378,
    name: 'yassithsbreeches',
    type: 'leggings',
    affix: 'viper',
    weight: 'light',
  },
  { id: 75388, name: 'maklainsrazor', type: 'dagger', affix: 'minstrel' },
  {
    id: 75573,
    name: 'zojjasclothbreather',
    type: 'helmaquatic',
    affix: 'berserker',
    weight: 'light',
  },
  {
    id: 75626,
    name: 'yassithsgrips',
    type: 'gloves',
    affix: 'viper',
    weight: 'medium',
  },
  { id: 75644, name: 'maklainsshortbow', type: 'shortbow', affix: 'minstrel' },
  {
    id: 75669,
    name: 'attunedringofreddeathinfused',
    type: 'ring',
    affix: 'berserker',
  },
  {
    id: 75770,
    name: 'yassithsmasque',
    type: 'helm',
    affix: 'viper',
    weight: 'light',
  },
  { id: 75820, name: 'maklainsbrazier', type: 'torch', affix: 'minstrel' },
  {
    id: 75866,
    name: 'maklainswristguards',
    type: 'gloves',
    affix: 'minstrel',
    weight: 'light',
  },
  {
    id: 76024,
    name: 'attunedcrystallinebandinfused',
    type: 'ring',
    affix: 'berserker',
  },
  { id: 76100, name: 'herald', type: 'rune' },
  { id: 76135, name: 'bowlofpricklypeartapiocapudding', type: 'food' },
  { id: 76166, name: 'tempest', type: 'rune' },
  { id: 76212, name: 'maklainsimpaler', type: 'harpoon', affix: 'minstrel' },
  { id: 76262, name: 'maklainswarhammer', type: 'hammer', affix: 'minstrel' },
  { id: 76271, name: 'yassithsbrazier', type: 'torch', affix: 'viper' },
  { id: 76302, name: 'jerkpoultryflatbreadsandwich', type: 'food' },
  { id: 76359, name: 'sliceofallspicecakewithicecream', type: 'food' },
  {
    id: 76377,
    name: 'yassithsbreastplate',
    type: 'coat',
    affix: 'viper',
    weight: 'heavy',
  },
  {
    id: 76403,
    name: 'tateossclothbreather',
    type: 'helmaquatic',
    affix: 'cleric',
    weight: 'light',
  },
  { id: 76415, name: 'bowlofchocolatetapiocapudding', type: 'food' },
  {
    id: 76501,
    name: 'maklainsclaymore',
    type: 'greatsword',
    affix: 'minstrel',
  },
  { id: 76599, name: 'thesisonmasterfulaccuracy', type: 'utility' },
  {
    id: 76658,
    name: 'maklainsshoulderguard',
    type: 'shoulders',
    affix: 'minstrel',
    weight: 'medium',
  },
  { id: 76688, name: 'yassithswand', type: 'scepter', affix: 'viper' },
  {
    id: 76710,
    name: 'yassithsguise',
    type: 'coat',
    affix: 'viper',
    weight: 'medium',
  },
  {
    id: 76729,
    name: 'maklainsgrips',
    type: 'gloves',
    affix: 'minstrel',
    weight: 'medium',
  },
  { id: 76730, name: 'maklainsblade', type: 'sword', affix: 'minstrel' },
  { id: 76738, name: 'thesisonmasterfulmalice', type: 'utility' },
  {
    id: 76776,
    name: 'yassithswarfists',
    type: 'gloves',
    affix: 'viper',
    weight: 'heavy',
  },
  { id: 76786, name: 'yassithsflangedmace', type: 'mace', affix: 'viper' },
  {
    id: 76809,
    name: 'attunedlunariacircleofthemooninfused',
    type: 'ring',
    affix: 'celestial',
  },
  { id: 76813, name: 'surging', type: 'rune' },
  { id: 76833, name: 'writofmasterfulaccuracy', type: 'utility' },
  {
    id: 76837,
    name: 'wupwupclothbreather',
    type: 'helmaquatic',
    affix: 'celestial',
    weight: 'light',
  },
  { id: 76840, name: 'bowloftapiocapudding', type: 'food' },
  {
    id: 77022,
    name: 'maklainstassets',
    type: 'leggings',
    affix: 'minstrel',
    weight: 'heavy',
  },
  {
    id: 77058,
    name: 'veratasmetalbreather',
    type: 'helmaquatic',
    affix: 'sinister',
    weight: 'heavy',
  },
  { id: 77122, name: 'yassithsreaver', type: 'axe', affix: 'viper' },
  {
    id: 77143,
    name: 'yassithstassets',
    type: 'leggings',
    affix: 'viper',
    weight: 'heavy',
  },
  { id: 77146, name: 'thesisonmasterfulstrength', type: 'utility' },
  {
    id: 77177,
    name: 'saphirsleatherbreather',
    type: 'helmaquatic',
    affix: 'assassin',
    weight: 'medium',
  },
  {
    id: 77204,
    name: 'maklainsstriders',
    type: 'boots',
    affix: 'minstrel',
    weight: 'medium',
  },
  { id: 77567, name: 'tuningicicle', type: 'utility' },
  { id: 77569, name: 'tinoffruitcake', type: 'utility' },
  { id: 77579, name: 'tropicalpeppermintcake', type: 'food' },
  { id: 77630, name: 'scoopofmintberryswirlicecream', type: 'food' },
  { id: 77632, name: 'peppermintoil', type: 'utility' },
  { id: 77643, name: 'peppermintomnomberrybar', type: 'food' },
  { id: 78305, name: 'superiorsharpeningstone', type: 'utility' },
  { id: 78658, name: 'mangopie', type: 'food' },
  { id: 78786, name: 'shiningbladebountynoticeruyethecrimson', type: 'gizmo' },
  { id: 78978, name: 'whitemantleportaldevice', type: 'gizmo' },
  { id: 79488, name: 'plateofsweetcurriedmussels', type: 'food' },
  { id: 79541, name: 'plateofislandpudding', type: 'food' },
  { id: 79748, name: 'winterberrypie', type: 'food' },
  { id: 79776, name: 'winterberrysorbet', type: 'food' },
  { id: 79786, name: 'steakwithwinterberrysauce', type: 'food' },
  { id: 79793, name: 'bowlofwinterberryseaweedsalad', type: 'food' },
  { id: 79988, name: 'superhotlemongrasspoultrysoup', type: 'food' },
  { id: 80056, name: 'superhotsaffronscentedpoultrysoup', type: 'food' },
  { id: 80116, name: 'thackeraysrifle', type: 'rifle', affix: 'seraph' },
  {
    id: 80132,
    name: 'thackeraysgreaves',
    type: 'boots',
    affix: 'seraph',
    weight: 'heavy',
  },
  { id: 80133, name: 'thackeraysbulwark', type: 'shield', affix: 'seraph' },
  {
    id: 80137,
    name: 'thackeraysshoulderguard',
    type: 'shoulders',
    affix: 'seraph',
    weight: 'medium',
  },
  { id: 80158, name: 'thackerayspillar', type: 'staff', affix: 'seraph' },
  { id: 80163, name: 'thackeraysslicer', type: 'dagger', affix: 'seraph' },
  {
    id: 80226,
    name: 'thackerayscrusader',
    type: 'greatsword',
    affix: 'seraph',
  },
  {
    id: 80227,
    name: 'thackeraysgauntlets',
    type: 'gloves',
    affix: 'seraph',
    weight: 'heavy',
  },
  {
    id: 80244,
    name: 'thackeraysdoublet',
    type: 'coat',
    affix: 'seraph',
    weight: 'light',
  },
  {
    id: 80268,
    name: 'thackeraysgloves',
    type: 'gloves',
    affix: 'seraph',
    weight: 'light',
  },
  {
    id: 80274,
    name: 'thackeraystassets',
    type: 'leggings',
    affix: 'seraph',
    weight: 'heavy',
  },
  {
    id: 80280,
    name: 'thackerayscuirass',
    type: 'coat',
    affix: 'seraph',
    weight: 'medium',
  },
  {
    id: 80300,
    name: 'thackeraysboots',
    type: 'boots',
    affix: 'seraph',
    weight: 'medium',
  },
  { id: 80318, name: 'thackerayscleaver', type: 'axe', affix: 'seraph' },
  {
    id: 80361,
    name: 'thackeraysbreastplate',
    type: 'coat',
    affix: 'seraph',
    weight: 'heavy',
  },
  {
    id: 80370,
    name: 'thackeraysvisage',
    type: 'helm',
    affix: 'seraph',
    weight: 'medium',
  },
  { id: 80373, name: 'lakedoricmussels', type: 'food' },
  { id: 80375, name: 'thackeraysrod', type: 'scepter', affix: 'seraph' },
  { id: 80391, name: 'thackerayscrescent', type: 'shortbow', affix: 'seraph' },
  { id: 80402, name: 'thackeraysgreatbow', type: 'longbow', affix: 'seraph' },
  { id: 80407, name: 'thackeraysbugle', type: 'warhorn', affix: 'seraph' },
  {
    id: 80448,
    name: 'thackeraysepaulets',
    type: 'shoulders',
    affix: 'seraph',
    weight: 'light',
  },
  {
    id: 80451,
    name: 'thackeraysbarbute',
    type: 'helm',
    affix: 'seraph',
    weight: 'heavy',
  },
  { id: 80466, name: 'saffronmussels', type: 'food' },
  { id: 80486, name: 'thackeraysfocus', type: 'focus', affix: 'seraph' },
  {
    id: 80491,
    name: 'thackeraysfootwear',
    type: 'boots',
    affix: 'seraph',
    weight: 'light',
  },
  { id: 80512, name: 'thackeraysgladius', type: 'sword', affix: 'seraph' },
  { id: 80520, name: 'thackerayshandcannon', type: 'pistol', affix: 'seraph' },
  { id: 80522, name: 'thackerayscrusher', type: 'hammer', affix: 'seraph' },
  {
    id: 80588,
    name: 'thackeraysvambraces',
    type: 'gloves',
    affix: 'seraph',
    weight: 'medium',
  },
  {
    id: 80616,
    name: 'thackerayspauldrons',
    type: 'shoulders',
    affix: 'seraph',
    weight: 'heavy',
  },
  { id: 80618, name: 'thackeraysspire', type: 'trident', affix: 'seraph' },
  { id: 80624, name: 'thackeraysgavel', type: 'mace', affix: 'seraph' },
  {
    id: 80637,
    name: 'thackeraysleggings',
    type: 'leggings',
    affix: 'seraph',
    weight: 'medium',
  },
  {
    id: 80661,
    name: 'thackeraysmasque',
    type: 'helm',
    affix: 'seraph',
    weight: 'light',
  },
  {
    id: 80664,
    name: 'thackerayspants',
    type: 'leggings',
    affix: 'seraph',
    weight: 'light',
  },
  { id: 80670, name: 'thackeraysskewer', type: 'harpoon', affix: 'seraph' },
  { id: 80683, name: 'thackeraysflame', type: 'torch', affix: 'seraph' },
  { id: 81034, name: 'magnanimoussharpeningstone', type: 'utility' },
  { id: 81045, name: 'bounty', type: 'sigil' },
  { id: 81079, name: 'magnanimoustuningcrystal', type: 'utility' },
  { id: 81091, name: 'naturesbounty', type: 'rune' },
  { id: 81157, name: 'magnanimousmaintenanceoil', type: 'utility' },
  { id: 81615, name: 'oysterswithcocktailsauce', type: 'food' },
  { id: 81621, name: 'oysterswithpestosauce', type: 'food' },
  { id: 81660, name: 'friedoystersandwich', type: 'food' },
  { id: 81786, name: 'oystersgnashblade', type: 'food' },
  { id: 81799, name: 'oysterswithzestysauce', type: 'food' },
  { id: 81867, name: 'oysterswithspicysauce', type: 'food' },
  { id: 82030, name: 'friedoysters', type: 'food' },
  { id: 82541, name: 'bowlofelonred', type: 'food' },
  { id: 82633, name: 'holosmith', type: 'rune' },
  { id: 82642, name: 'cupoflightroastedcoffee', type: 'food' },
  {
    id: 82705,
    name: 'attunedsigilofthefoolinfused',
    type: 'ring',
    affix: 'harrier',
  },
  { id: 82769, name: 'gorenseeltoothcharm', type: 'amulet', affix: 'harrier' },
  { id: 82791, name: 'deadeye', type: 'rune' },
  { id: 82876, name: 'frenzy', type: 'sigil' },
  {
    id: 82897,
    name: 'jahnussstainedpectoral',
    type: 'amulet',
    affix: 'grieving',
  },
  { id: 83338, name: 'firebrand', type: 'rune' },
  { id: 83367, name: 'cavalier', type: 'rune' },
  { id: 83404, name: 'mourningbell', type: 'accessory', affix: 'grieving' },
  { id: 83423, name: 'weaver', type: 'rune' },
  {
    id: 83429,
    name: 'eloniantransitpass',
    type: 'accessory',
    affix: 'harrier',
  },
  { id: 83502, name: 'renegade', type: 'rune' },
  { id: 83663, name: 'scourge', type: 'rune' },
  {
    id: 83675,
    name: 'attunedcorsairsringinfused',
    type: 'ring',
    affix: 'harrier',
  },
  { id: 83955, name: 'bowlofredlentilsoup', type: 'food' },
  { id: 83964, name: 'soulbeast', type: 'rune' },
  { id: 84127, name: 'mirage', type: 'rune' },
  { id: 84171, name: 'rebirth', type: 'rune' },
  {
    id: 84212,
    name: 'attunedkolestormentedeyeinfused',
    type: 'ring',
    affix: 'grieving',
  },
  { id: 84505, name: 'severance', type: 'sigil' },
  {
    id: 84577,
    name: 'attunedgiftofthehiddenscioninfused',
    type: 'ring',
    affix: 'grieving',
  },
  { id: 84749, name: 'spellbreaker', type: 'rune' },
  { id: 84876, name: 'thetwinsblade', type: 'sword', affix: 'grieving' },
  { id: 84878, name: 'zehtukasrevolver', type: 'pistol', affix: 'harrier' },
  {
    id: 84879,
    name: 'zehtukasvisor',
    type: 'helm',
    affix: 'harrier',
    weight: 'heavy',
  },
  {
    id: 84911,
    name: 'thetwinstassets',
    type: 'leggings',
    affix: 'grieving',
    weight: 'heavy',
  },
  { id: 84912, name: 'zehtukasflangedmace', type: 'mace', affix: 'harrier' },
  {
    id: 84923,
    name: 'zehtukasguise',
    type: 'coat',
    affix: 'harrier',
    weight: 'medium',
  },
  {
    id: 84926,
    name: 'zehtukasbreeches',
    type: 'leggings',
    affix: 'harrier',
    weight: 'light',
  },
  { id: 84931, name: 'thetwinsrevolver', type: 'pistol', affix: 'grieving' },
  { id: 84936, name: 'thetwinsrazor', type: 'dagger', affix: 'grieving' },
  { id: 84939, name: 'zehtukasblade', type: 'sword', affix: 'harrier' },
  {
    id: 84944,
    name: 'thetwinsharpoongun',
    type: 'speargun',
    affix: 'grieving',
  },
  { id: 84957, name: 'zehtukasbastion', type: 'shield', affix: 'harrier' },
  { id: 84973, name: 'zehtukasherald', type: 'warhorn', affix: 'harrier' },
  {
    id: 84983,
    name: 'zehtukasgrips',
    type: 'gloves',
    affix: 'harrier',
    weight: 'medium',
  },
  { id: 85001, name: 'thetwinsspire', type: 'staff', affix: 'grieving' },
  {
    id: 85004,
    name: 'zehtukaswristguards',
    type: 'gloves',
    affix: 'harrier',
    weight: 'light',
  },
  { id: 85006, name: 'thetwinsbrazier', type: 'torch', affix: 'grieving' },
  {
    id: 85007,
    name: 'thetwinsfootwear',
    type: 'boots',
    affix: 'grieving',
    weight: 'light',
  },
  { id: 85013, name: 'zehtukasbrazier', type: 'torch', affix: 'harrier' },
  {
    id: 85019,
    name: 'thetwinsclaymore',
    type: 'greatsword',
    affix: 'grieving',
  },
  {
    id: 85024,
    name: 'zehtukastassets',
    type: 'leggings',
    affix: 'harrier',
    weight: 'heavy',
  },
  { id: 85027, name: 'zehtukaswand', type: 'scepter', affix: 'harrier' },
  { id: 85036, name: 'zehtukasharpoongun', type: 'speargun', affix: 'harrier' },
  {
    id: 85042,
    name: 'thetwinsbreastplate',
    type: 'coat',
    affix: 'grieving',
    weight: 'heavy',
  },
  { id: 85044, name: 'thetwinsartifact', type: 'focus', affix: 'grieving' },
  { id: 85047, name: 'zehtukasreaver', type: 'axe', affix: 'harrier' },
  {
    id: 85048,
    name: 'thetwinswristguards',
    type: 'gloves',
    affix: 'grieving',
    weight: 'light',
  },
  { id: 85051, name: 'zehtukasrazor', type: 'dagger', affix: 'harrier' },
  {
    id: 85054,
    name: 'thetwinsshoulderguard',
    type: 'shoulders',
    affix: 'grieving',
    weight: 'medium',
  },
  {
    id: 85062,
    name: 'thetwinsguise',
    type: 'coat',
    affix: 'grieving',
    weight: 'medium',
  },
  {
    id: 85067,
    name: 'thetwinsvisage',
    type: 'helm',
    affix: 'grieving',
    weight: 'medium',
  },
  { id: 85072, name: 'thetwinsmusket', type: 'rifle', affix: 'grieving' },
  { id: 85074, name: 'thetwinsherald', type: 'warhorn', affix: 'grieving' },
  { id: 85076, name: 'thetwinswand', type: 'scepter', affix: 'grieving' },
  {
    id: 85089,
    name: 'zehtukasepaulets',
    type: 'shoulders',
    affix: 'harrier',
    weight: 'light',
  },
  {
    id: 85093,
    name: 'thetwinsgreaves',
    type: 'boots',
    affix: 'grieving',
    weight: 'heavy',
  },
  { id: 85094, name: 'thetwinstrident', type: 'trident', affix: 'grieving' },
  {
    id: 85098,
    name: 'zehtukasdoublet',
    type: 'coat',
    affix: 'harrier',
    weight: 'light',
  },
  { id: 85111, name: 'zehtukasgreatbow', type: 'longbow', affix: 'harrier' },
  { id: 85112, name: 'zehtukasspire', type: 'staff', affix: 'harrier' },
  { id: 85121, name: 'zehtukasclaymore', type: 'greatsword', affix: 'harrier' },
  {
    id: 85126,
    name: 'zehtukasbreastplate',
    type: 'coat',
    affix: 'harrier',
    weight: 'heavy',
  },
  { id: 85131, name: 'zehtukasimpaler', type: 'harpoon', affix: 'harrier' },
  {
    id: 85149,
    name: 'zehtukasleggings',
    type: 'leggings',
    affix: 'harrier',
    weight: 'medium',
  },
  {
    id: 85161,
    name: 'zehtukasmasque',
    type: 'helm',
    affix: 'harrier',
    weight: 'light',
  },
  {
    id: 85172,
    name: 'zehtukasvisage',
    type: 'helm',
    affix: 'harrier',
    weight: 'medium',
  },
  {
    id: 85183,
    name: 'zehtukasshoulderguard',
    type: 'shoulders',
    affix: 'harrier',
    weight: 'medium',
  },
  {
    id: 85196,
    name: 'zehtukasgreaves',
    type: 'boots',
    affix: 'harrier',
    weight: 'heavy',
  },
  { id: 85200, name: 'zehtukasshortbow', type: 'shortbow', affix: 'harrier' },
  {
    id: 85208,
    name: 'thetwinsgrips',
    type: 'gloves',
    affix: 'grieving',
    weight: 'medium',
  },
  { id: 85212, name: 'thetwinsgreatbow', type: 'longbow', affix: 'grieving' },
  { id: 85228, name: 'zehtukaswarhammer', type: 'hammer', affix: 'harrier' },
  {
    id: 85241,
    name: 'thetwinsepaulets',
    type: 'shoulders',
    affix: 'grieving',
    weight: 'light',
  },
  { id: 85242, name: 'thetwinsshortbow', type: 'shortbow', affix: 'grieving' },
  { id: 85244, name: 'endlesschoyapiatatonic', type: 'gizmo' },
  { id: 85249, name: 'thetwinswarhammer', type: 'hammer', affix: 'grieving' },
  { id: 85253, name: 'thetwinsreaver', type: 'axe', affix: 'grieving' },
  { id: 85254, name: 'thetwinsimpaler', type: 'harpoon', affix: 'grieving' },
  { id: 85266, name: 'thetwinsbastion', type: 'shield', affix: 'grieving' },
  {
    id: 85286,
    name: 'zehtukaspauldrons',
    type: 'shoulders',
    affix: 'harrier',
    weight: 'heavy',
  },
  { id: 85295, name: 'thetwinsflangedmace', type: 'mace', affix: 'grieving' },
  {
    id: 85296,
    name: 'thetwinsmasque',
    type: 'helm',
    affix: 'grieving',
    weight: 'light',
  },
  {
    id: 85300,
    name: 'thetwinswarfists',
    type: 'gloves',
    affix: 'grieving',
    weight: 'heavy',
  },
  {
    id: 85308,
    name: 'thetwinsstriders',
    type: 'boots',
    affix: 'grieving',
    weight: 'medium',
  },
  {
    id: 85317,
    name: 'zehtukasfootwear',
    type: 'boots',
    affix: 'harrier',
    weight: 'light',
  },
  {
    id: 85319,
    name: 'thetwinsdoublet',
    type: 'coat',
    affix: 'grieving',
    weight: 'light',
  },
  {
    id: 85324,
    name: 'thetwinsleggings',
    type: 'leggings',
    affix: 'grieving',
    weight: 'medium',
  },
  {
    id: 85330,
    name: 'zehtukaswarfists',
    type: 'gloves',
    affix: 'harrier',
    weight: 'heavy',
  },
  {
    id: 85343,
    name: 'zehtukasstriders',
    type: 'boots',
    affix: 'harrier',
    weight: 'medium',
  },
  { id: 85345, name: 'zehtukastrident', type: 'trident', affix: 'harrier' },
  { id: 85346, name: 'zehtukasartifact', type: 'focus', affix: 'harrier' },
  { id: 85348, name: 'zehtukasmusket', type: 'rifle', affix: 'harrier' },
  {
    id: 85350,
    name: 'thetwinsvisor',
    type: 'helm',
    affix: 'grieving',
    weight: 'heavy',
  },
  {
    id: 85352,
    name: 'thetwinsbreeches',
    type: 'leggings',
    affix: 'grieving',
    weight: 'light',
  },
  {
    id: 85355,
    name: 'thetwinspauldrons',
    type: 'shoulders',
    affix: 'grieving',
    weight: 'heavy',
  },
  { id: 85527, name: 'spellbreaker', type: 'rune' },
  { id: 85559, name: 'renegade', type: 'rune' },
  { id: 85573, name: 'deadeye', type: 'rune' },
  { id: 85578, name: 'firebrand', type: 'rune' },
  { id: 85588, name: 'weaver', type: 'rune' },
  { id: 85602, name: 'mirage', type: 'rune' },
  { id: 85606, name: 'soulbeast', type: 'rune' },
  { id: 85617, name: 'holosmith', type: 'rune' },
  { id: 85713, name: 'stars', type: 'rune' },
  { id: 86016, name: 'corsairmaintenanceoil', type: 'utility' },
  { id: 86113, name: 'spitefulagonyinfusion', type: 'infusion' },
  { id: 86170, name: 'stars', type: 'sigil' },
  { id: 86180, name: 'mysticalagonyinfusion', type: 'infusion' },
  { id: 86287, name: 'corsairtuningcrystal', type: 'utility' },
  { id: 86378, name: 'corsairsharpeningstone', type: 'utility' },
  { id: 86997, name: 'plateofbeefrendang', type: 'food' },
  { id: 87076, name: 'bowlofpoultrysatay', type: 'food' },
  { id: 87329, name: 'holographicsuperdrumstick', type: 'utility' },
  { id: 87336, name: 'holographicsuperapple', type: 'utility' },
  { id: 87358, name: 'holographicsupercheese', type: 'utility' },
  { id: 87367, name: 'holographicsupercake', type: 'food' },
  { id: 88118, name: 'zephyrite', type: 'rune' },
  {
    id: 88376,
    name: 'yassithsmetalbreather',
    type: 'helmaquatic',
    affix: 'viper',
    weight: 'heavy',
  },
  {
    id: 88400,
    name: 'yassithsclothbreather',
    type: 'helmaquatic',
    affix: 'viper',
    weight: 'light',
  },
  {
    id: 88420,
    name: 'yassithsleatherbreather',
    type: 'helmaquatic',
    affix: 'viper',
    weight: 'medium',
  },
  {
    id: 88427,
    name: 'maklainsclothbreather',
    type: 'helmaquatic',
    affix: 'minstrel',
    weight: 'light',
  },
  {
    id: 88432,
    name: 'thackeraysleatherbreather',
    type: 'helmaquatic',
    affix: 'seraph',
    weight: 'medium',
  },
  {
    id: 88440,
    name: 'thackeraysmetalbreather',
    type: 'helmaquatic',
    affix: 'seraph',
    weight: 'heavy',
  },
  {
    id: 88443,
    name: 'maklainsleatherbreather',
    type: 'helmaquatic',
    affix: 'minstrel',
    weight: 'medium',
  },
  {
    id: 88445,
    name: 'maklainsmetalbreather',
    type: 'helmaquatic',
    affix: 'minstrel',
    weight: 'heavy',
  },
  {
    id: 88466,
    name: 'thackeraysclothbreather',
    type: 'helmaquatic',
    affix: 'seraph',
    weight: 'light',
  },
  { id: 89002, name: 'soulpastry', type: 'food' },
  { id: 89157, name: 'enhancedlucentoil', type: 'utility' },
  { id: 89203, name: 'potentlucentoil', type: 'utility' },
  {
    id: 89441,
    name: 'heroicdragonsbloodshield',
    type: 'shield',
    affix: 'diviner',
  },
  {
    id: 89446,
    name: 'heroicdragonsbloodstaff',
    type: 'staff',
    affix: 'diviner',
  },
  {
    id: 89452,
    name: 'steelstarsfootwear',
    type: 'boots',
    affix: 'diviner',
    weight: 'light',
  },
  {
    id: 89460,
    name: 'steelstarstassets',
    type: 'leggings',
    affix: 'diviner',
    weight: 'heavy',
  },
  { id: 89461, name: 'dragoncrystalpotion', type: 'utility' },
  { id: 89484, name: 'steelstarswand', type: 'scepter', affix: 'diviner' },
  {
    id: 89503,
    name: 'heroicdragonsbloodlongbow',
    type: 'longbow',
    affix: 'diviner',
  },
  {
    id: 89528,
    name: 'steelstarsguise',
    type: 'coat',
    affix: 'diviner',
    weight: 'medium',
  },
  { id: 89544, name: 'dagnarsbadge', type: 'accessory', affix: 'diviner' },
  {
    id: 89566,
    name: 'heroicdragonsbloodsword',
    type: 'sword',
    affix: 'diviner',
  },
  {
    id: 89592,
    name: 'heroicdragonsbloodwarhorn',
    type: 'warhorn',
    affix: 'diviner',
  },
  { id: 89610, name: 'steelstarsimpaler', type: 'harpoon', affix: 'diviner' },
  { id: 89612, name: 'steelstarsbrazier', type: 'torch', affix: 'diviner' },
  {
    id: 89628,
    name: 'steelstarsepaulets',
    type: 'shoulders',
    affix: 'diviner',
    weight: 'light',
  },
  { id: 89632, name: 'heroicdragonsbloodaxe', type: 'axe', affix: 'diviner' },
  {
    id: 89647,
    name: 'heroicdragonsbloodpistol',
    type: 'pistol',
    affix: 'diviner',
  },
  {
    id: 89656,
    name: 'steelstarsgreaves',
    type: 'boots',
    affix: 'diviner',
    weight: 'heavy',
  },
  {
    id: 89706,
    name: 'steelstarsclaymore',
    type: 'greatsword',
    affix: 'diviner',
  },
  { id: 89707, name: 'steelstarsflangedmace', type: 'mace', affix: 'diviner' },
  {
    id: 89733,
    name: 'steelstarsbreastplate',
    type: 'coat',
    affix: 'diviner',
    weight: 'heavy',
  },
  { id: 89736, name: 'steelstarsmusket', type: 'rifle', affix: 'diviner' },
  { id: 89759, name: 'frodakssteelstar', type: 'amulet', affix: 'diviner' },
  {
    id: 89768,
    name: 'steelstarsdoublet',
    type: 'coat',
    affix: 'diviner',
    weight: 'light',
  },
  { id: 89773, name: 'steelstarswarhammer', type: 'hammer', affix: 'diviner' },
  {
    id: 89785,
    name: 'steelstarspauldrons',
    type: 'shoulders',
    affix: 'diviner',
    weight: 'heavy',
  },
  {
    id: 89787,
    name: 'heroicdragonsblooddagger',
    type: 'dagger',
    affix: 'diviner',
  },
  {
    id: 89789,
    name: 'steelstarsshoulderguard',
    type: 'shoulders',
    affix: 'diviner',
    weight: 'medium',
  },
  {
    id: 89810,
    name: 'steelstarsharpoongun',
    type: 'speargun',
    affix: 'diviner',
  },
  {
    id: 89821,
    name: 'heroicdragonsbloodfocus',
    type: 'focus',
    affix: 'diviner',
  },
  {
    id: 89822,
    name: 'steelstarswarfists',
    type: 'gloves',
    affix: 'diviner',
    weight: 'heavy',
  },
  {
    id: 89826,
    name: 'heroicdragonsbloodshortbow',
    type: 'shortbow',
    affix: 'diviner',
  },
  {
    id: 89893,
    name: 'steelstarsstriders',
    type: 'boots',
    affix: 'diviner',
    weight: 'medium',
  },
  { id: 89904, name: 'steelstarstrident', type: 'trident', affix: 'diviner' },
  {
    id: 89912,
    name: 'steelstarsmasque',
    type: 'helm',
    affix: 'diviner',
    weight: 'light',
  },
  {
    id: 89924,
    name: 'steelstarsvisor',
    type: 'helm',
    affix: 'diviner',
    weight: 'heavy',
  },
  {
    id: 89925,
    name: 'steelstarswristguards',
    type: 'gloves',
    affix: 'diviner',
    weight: 'light',
  },
  {
    id: 89934,
    name: 'steelstarsleggings',
    type: 'leggings',
    affix: 'diviner',
    weight: 'medium',
  },
  {
    id: 89940,
    name: 'steelstarsbreeches',
    type: 'leggings',
    affix: 'diviner',
    weight: 'light',
  },
  {
    id: 89969,
    name: 'steelstarsvisage',
    type: 'helm',
    affix: 'diviner',
    weight: 'medium',
  },
  {
    id: 89985,
    name: 'steelstarsgrips',
    type: 'gloves',
    affix: 'diviner',
    weight: 'medium',
  },
  { id: 89999, name: 'fireworks', type: 'rune' },
  { id: 91289, name: 'powerfulpotionofbrandedslaying', type: 'utility' },
  { id: 91339, name: 'hologramslaying', type: 'sigil' },
  { id: 91350, name: 'powerfulpotionofmordremslaying', type: 'utility' },
  { id: 91842, name: 'plateofeggsbenedict', type: 'food' },
  { id: 91917, name: 'plateofspicymoawings', type: 'food' },
  { id: 91950, name: 'bowloffirebreatherchili', type: 'food' },
  { id: 92138, name: 'saintbones', type: 'food' },
  { id: 92196, name: 'soulcake', type: 'food' },
  { id: 95276, name: 'plushkralky', type: 'accessory', affix: 'diviner' },
  { id: 95318, name: 'plushzhaia', type: 'accessory', affix: 'grieving' },
  {
    id: 95583,
    name: 'suunsgreaves',
    type: 'boots',
    affix: 'dragon',
    weight: 'heavy',
  },
  {
    id: 95605,
    name: 'suunsvisor',
    type: 'helm',
    affix: 'dragon',
    weight: 'heavy',
  },
  {
    id: 95626,
    name: 'suunsdoublet',
    type: 'coat',
    affix: 'dragon',
    weight: 'light',
  },
  { id: 95667, name: 'suunsartifact', type: 'focus', affix: 'dragon' },
  { id: 95687, name: 'jadepunkrifle', type: 'rifle', affix: 'dragon' },
  {
    id: 95714,
    name: 'togosleggings',
    type: 'leggings',
    affix: 'ritualist',
    weight: 'medium',
  },
  { id: 95749, name: 'suunsherald', type: 'warhorn', affix: 'dragon' },
  { id: 95781, name: 'togosreaver', type: 'axe', affix: 'ritualist' },
  { id: 95785, name: 'jadepunktorch', type: 'torch', affix: 'dragon' },
  { id: 95852, name: 'suunsrevolver', type: 'pistol', affix: 'dragon' },
  { id: 95892, name: 'kurzickbrooch', type: 'amulet', affix: 'ritualist' },
  { id: 95942, name: 'meatyasparagusskewer', type: 'food' },
  { id: 95963, name: 'jadepunkaxe', type: 'axe', affix: 'dragon' },
  { id: 95985, name: 'jadepunkscepter', type: 'scepter', affix: 'dragon' },
  { id: 95987, name: 'suunsbastion', type: 'shield', affix: 'dragon' },
  { id: 95996, name: 'luxonbrooch', type: 'amulet', affix: 'dragon' },
  {
    id: 96005,
    name: 'togosmasque',
    type: 'helm',
    affix: 'ritualist',
    weight: 'light',
  },
  { id: 96029, name: 'suunsharpoongun', type: 'speargun', affix: 'dragon' },
  { id: 96042, name: 'suunsflangedmace', type: 'mace', affix: 'dragon' },
  { id: 96044, name: 'togosflangedmace', type: 'mace', affix: 'ritualist' },
  {
    id: 96062,
    name: 'suunsfootwear',
    type: 'boots',
    affix: 'dragon',
    weight: 'light',
  },
  {
    id: 96114,
    name: 'togospauldrons',
    type: 'shoulders',
    affix: 'ritualist',
    weight: 'heavy',
  },
  {
    id: 96140,
    name: 'togoswristguards',
    type: 'gloves',
    affix: 'ritualist',
    weight: 'light',
  },
  { id: 96199, name: 'travelingtankard', type: 'accessory', affix: 'dragon' },
  {
    id: 96230,
    name: 'suunsleggings',
    type: 'leggings',
    affix: 'dragon',
    weight: 'medium',
  },
  {
    id: 96236,
    name: 'suunsshoulderguard',
    type: 'shoulders',
    affix: 'dragon',
    weight: 'medium',
  },
  {
    id: 96278,
    name: 'togosbreastplate',
    type: 'coat',
    affix: 'ritualist',
    weight: 'heavy',
  },
  { id: 96387, name: 'jadepunkshortbow', type: 'shortbow', affix: 'dragon' },
  { id: 96417, name: 'suunstrident', type: 'trident', affix: 'dragon' },
  {
    id: 96431,
    name: 'suunsguise',
    type: 'coat',
    affix: 'dragon',
    weight: 'medium',
  },
  { id: 96433, name: 'togosclaymore', type: 'greatsword', affix: 'ritualist' },
  { id: 96518, name: 'jadepunklongbow', type: 'longbow', affix: 'dragon' },
  { id: 96525, name: 'togosimpaler', type: 'harpoon', affix: 'ritualist' },
  { id: 96528, name: 'togosshortbow', type: 'shortbow', affix: 'ritualist' },
  { id: 96544, name: 'togosherald', type: 'warhorn', affix: 'ritualist' },
  { id: 96578, name: 'plateofkimchipancakes', type: 'food' },
  { id: 96691, name: 'togoswarhammer', type: 'hammer', affix: 'ritualist' },
  { id: 96707, name: 'bowloffishstew', type: 'food' },
  {
    id: 96711,
    name: 'togosvisor',
    type: 'helm',
    affix: 'ritualist',
    weight: 'heavy',
  },
  {
    id: 96731,
    name: 'suunsepaulets',
    type: 'shoulders',
    affix: 'dragon',
    weight: 'light',
  },
  {
    id: 96739,
    name: 'togosfootwear',
    type: 'boots',
    affix: 'ritualist',
    weight: 'light',
  },
  {
    id: 96780,
    name: 'suunsstriders',
    type: 'boots',
    affix: 'dragon',
    weight: 'medium',
  },
  { id: 96781, name: 'jadepunksword', type: 'sword', affix: 'dragon' },
  { id: 96793, name: 'blockoftofu', type: 'food' },
  {
    id: 96795,
    name: 'togosgrips',
    type: 'gloves',
    affix: 'ritualist',
    weight: 'medium',
  },
  {
    id: 96818,
    name: 'suunsbreeches',
    type: 'leggings',
    affix: 'dragon',
    weight: 'light',
  },
  { id: 96821, name: 'togosrazor', type: 'dagger', affix: 'ritualist' },
  {
    id: 96832,
    name: 'suunsvisage',
    type: 'helm',
    affix: 'dragon',
    weight: 'medium',
  },
  { id: 96869, name: 'togosspire', type: 'staff', affix: 'ritualist' },
  { id: 96916, name: 'meatyricebowl', type: 'food' },
  {
    id: 96932,
    name: 'togosgreaves',
    type: 'boots',
    affix: 'ritualist',
    weight: 'heavy',
  },
  {
    id: 96962,
    name: 'togosdoublet',
    type: 'coat',
    affix: 'ritualist',
    weight: 'light',
  },
  {
    id: 96966,
    name: 'suunspauldrons',
    type: 'shoulders',
    affix: 'dragon',
    weight: 'heavy',
  },
  {
    id: 96967,
    name: 'togoswarfist',
    type: 'gloves',
    affix: 'ritualist',
    weight: 'heavy',
  },
  { id: 96974, name: 'suunsimpaler', type: 'harpoon', affix: 'dragon' },
  {
    id: 96994,
    name: 'jadepunkgreatsword',
    type: 'greatsword',
    affix: 'dragon',
  },
  { id: 97000, name: 'jadepunkstaff', type: 'staff', affix: 'dragon' },
  {
    id: 97154,
    name: 'togosguise',
    type: 'coat',
    affix: 'ritualist',
    weight: 'medium',
  },
  { id: 97156, name: 'suunswarhammer', type: 'hammer', affix: 'dragon' },
  {
    id: 97161,
    name: 'suunsmasque',
    type: 'helm',
    affix: 'dragon',
    weight: 'light',
  },
  { id: 97180, name: 'togosharpoongun', type: 'speargun', affix: 'ritualist' },
  { id: 97272, name: 'togoswand', type: 'scepter', affix: 'ritualist' },
  { id: 97295, name: 'suunsrazor', type: 'dagger', affix: 'dragon' },
  {
    id: 97313,
    name: 'togosepaulets',
    type: 'shoulders',
    affix: 'ritualist',
    weight: 'light',
  },
  {
    id: 97322,
    name: 'storytellerslute',
    type: 'accessory',
    affix: 'ritualist',
  },
  {
    id: 97390,
    name: 'suunswristguards',
    type: 'gloves',
    affix: 'dragon',
    weight: 'light',
  },
  {
    id: 97395,
    name: 'togosstriders',
    type: 'boots',
    affix: 'ritualist',
    weight: 'medium',
  },
  { id: 97422, name: 'bowlofkimchitofustew', type: 'food' },
  { id: 97425, name: 'togosbastion', type: 'shield', affix: 'ritualist' },
  {
    id: 97440,
    name: 'togosvisage',
    type: 'helm',
    affix: 'ritualist',
    weight: 'medium',
  },
  {
    id: 97476,
    name: 'togosbreeches',
    type: 'leggings',
    affix: 'ritualist',
    weight: 'light',
  },
  { id: 97508, name: 'togosrevolver', type: 'pistol', affix: 'ritualist' },
  {
    id: 97540,
    name: 'suunstassets',
    type: 'leggings',
    affix: 'dragon',
    weight: 'heavy',
  },
  { id: 97555, name: 'togostrident', type: 'trident', affix: 'ritualist' },
  {
    id: 97663,
    name: 'suunsgrips',
    type: 'gloves',
    affix: 'dragon',
    weight: 'medium',
  },
  {
    id: 97680,
    name: 'suunswarfist',
    type: 'gloves',
    affix: 'dragon',
    weight: 'heavy',
  },
  { id: 97681, name: 'togosblade', type: 'sword', affix: 'ritualist' },
  {
    id: 97710,
    name: 'togostassets',
    type: 'leggings',
    affix: 'ritualist',
    weight: 'heavy',
  },
  { id: 97752, name: 'togosbrazier', type: 'torch', affix: 'ritualist' },
  { id: 97767, name: 'fishyricebowl', type: 'food' },
  { id: 97771, name: 'redfishsushi', type: 'food' },
  {
    id: 97812,
    name: 'suunsbreastplate',
    type: 'coat',
    affix: 'dragon',
    weight: 'heavy',
  },
  { id: 97831, name: 'togosartifact', type: 'focus', affix: 'ritualist' },
  {
    id: 97862,
    name: 'togosshoulderguard',
    type: 'shoulders',
    affix: 'ritualist',
    weight: 'medium',
  },
];
